"use client";

import { useActionState } from "react";
import { createSceneAction, deleteSceneAction, updateSceneAction } from "@/app/actions";
import type { FormState } from "@/app/actions";
import { projectStatuses } from "@/lib/db/enums";

type Scene = { id: string; code: string; sceneNumber: number; title: string; location: string; description: string; durationTarget: number | null; status: (typeof projectStatuses)[number]; shotCount: number };
const labels: Record<(typeof projectStatuses)[number], string> = { NOT_STARTED: "Belum dimulai", IN_PROGRESS: "Berjalan", APPROVED: "Disetujui", NEEDS_REVISION: "Perlu revisi", BLOCKED: "Terhambat", FINAL: "Final" };

export function SceneManager({ projectId, contentId, scenes, suggested }: { projectId: string; contentId: string; scenes: Scene[]; suggested: { code: string; sceneNumber: number } }) {
  const [state, action, pending] = useActionState(createSceneAction, {});
  return <div className="scene-list">
    <details className="detail-panel"><summary className="text-link">＋ Tambah adegan</summary><form action={action} className="inline-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="contentId" value={contentId}/><div className="small-form-grid"><label className="field"><span>Kode adegan</span><input name="code" defaultValue={suggested.code} required/></label><label className="field"><span>Nomor</span><input type="number" name="sceneNumber" min="1" defaultValue={suggested.sceneNumber} required/></label><label className="field field-wide"><span>Judul</span><input name="title" required maxLength={160}/></label><label className="field"><span>Lokasi</span><input name="location" maxLength={160}/></label><label className="field"><span>Durasi target (detik)</span><input name="durationTarget" type="number" min="0.1" step="0.1"/></label><label className="field field-wide"><span>Deskripsi</span><textarea name="description" rows={2}/></label><input type="hidden" name="status" value="NOT_STARTED"/></div>{state.error&&<p className="form-error" role="alert">{state.error}</p>}<button className="button button-primary" disabled={pending}>{pending?"Menyimpan…":"Simpan adegan"}</button></form></details>
    {scenes.length===0?<div className="empty-inline">Adegan bersifat opsional. Shot dapat dibuat tanpa adegan.</div>:scenes.map((scene)=><SceneRow key={scene.id} projectId={projectId} contentId={contentId} scene={scene}/>)}
  </div>;
}

function SceneRow({ projectId, contentId, scene }: { projectId: string; contentId: string; scene: Scene }) {
  const [editState, editAction, editing] = useActionState(updateSceneAction, {});
  const [deleteState, deleteAction, deleting] = useActionState(deleteSceneAction, {} satisfies FormState);
  return <article className="scene-row"><div className="scene-row-top"><div><h3><code>{scene.code}</code> · {scene.title}</h3><p>{scene.location||"Lokasi belum diisi"} · {scene.shotCount} shot · {labels[scene.status]}</p></div><div className="scene-row-actions"><details><summary className="text-link">Edit</summary><form action={editAction} className="inline-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="contentId" value={contentId}/><input type="hidden" name="sceneId" value={scene.id}/><div className="small-form-grid"><label className="field"><span>Kode</span><input name="code" defaultValue={scene.code} required/></label><label className="field"><span>Nomor</span><input name="sceneNumber" type="number" min="1" defaultValue={scene.sceneNumber} required/></label><label className="field field-wide"><span>Judul</span><input name="title" defaultValue={scene.title} required/></label><label className="field"><span>Lokasi</span><input name="location" defaultValue={scene.location}/></label><label className="field"><span>Durasi (detik)</span><input name="durationTarget" type="number" min="0.1" step="0.1" defaultValue={scene.durationTarget??""}/></label><label className="field field-wide"><span>Deskripsi</span><textarea name="description" rows={2} defaultValue={scene.description}/></label><label className="field field-wide"><span>Status</span><select name="status" defaultValue={scene.status}>{projectStatuses.map((status)=><option key={status} value={status}>{labels[status]}</option>)}</select></label></div>{editState.error&&<p className="form-error">{editState.error}</p>}<button className="button button-primary" disabled={editing}>{editing?"Menyimpan…":"Simpan"}</button></form></details>
      <details><summary className="text-link">Hapus</summary><form action={deleteAction} className="danger-zone"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="contentId" value={contentId}/><input type="hidden" name="sceneId" value={scene.id}/>{scene.shotCount>0&&<><p>Adegan ini memiliki {scene.shotCount} shot. Jika dihapus, shot tetap tersimpan tetapi tidak lagi terhubung ke adegan.</p><label><input type="checkbox" name="confirmWithShots" required/>Saya mengerti, hapus adegan dan lepaskan shot terkait.</label></>}{deleteState.error&&<p className="form-error">{deleteState.error}</p>}<button className="danger-button" disabled={deleting}>{deleting?"Menghapus…":"Konfirmasi hapus adegan"}</button></form></details></div></div>
    <div className="scene-list-meta"><span>{scene.durationTarget?`${scene.durationTarget} dtk`:"Durasi belum ditentukan"}</span><span>{labels[scene.status]}</span></div>
  </article>;
}
